// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqrRVnjdRIrQ-ZzZaZXBpGVEDqP77W0mI',
    appId: '1:862963623225:android:d8df8214a5d5cd8770b4e8',
    messagingSenderId: '862963623225',
    projectId: 'albert-softwarica-test-1001',
    databaseURL: 'https://albert-softwarica-test-1001-default-rtdb.firebaseio.com',
    storageBucket: 'albert-softwarica-test-1001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnI5OOrXH1owBqoFLNHUeWw9RI_TDjv_o',
    appId: '1:862963623225:ios:59e69aa52ec518e570b4e8',
    messagingSenderId: '862963623225',
    projectId: 'albert-softwarica-test-1001',
    databaseURL: 'https://albert-softwarica-test-1001-default-rtdb.firebaseio.com',
    storageBucket: 'albert-softwarica-test-1001.appspot.com',
    iosClientId: '862963623225-s4ld8jqv257pntgoibst6dl9gp292jco.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );
}
